### ISSUE TITLE
为啥我转换的时候输出是none。我是用的4b不是4chat，和这有关系吗？

### ISSUE THREAD

**Issue by txl0117** [modelscope/dash-infer#13]
![image](https://github.com/modelscope/dash-infer/assets/71427899/f23cd445-651a-4dc0-9c3f-c8142b910a4b)

**Comment by txl0117** [comment]
![image](https://github.com/modelscope/dash-infer/assets/71427899/7cfb6efa-16f4-4d69-8042-2e8bf46ba32e)

**Comment by txl0117** [comment]
![image](https://github.com/modelscope/dash-infer/assets/71427899/20d11d28-d64c-431b-9bde-ed748ea66c78)

**Comment by laiwenzh** [comment]
“could not create a primitive descriptor for a matmul primitive”，看起来是你的cpu不支持bf16计算，可以把config文件里的"matmul_precision": "medium"改成"matmul_precision": "highest"

**Comment by txl0117** [comment]
![image](https://github.com/modelscope/dash-infer/assets/71427899/11ee2009-5e0c-4858-9254-85c9f024c4f0)
谢谢大佬，可我改了以后还是有个错误信息显示 Illegal instruction (核心已转储)

**Comment by leefige** [comment]
Illegal instruction 可以参考 #3
