### ISSUE TITLE
我用阿里g8i机器还是没法复现官方的首字延迟速度，请问官方的速度是在定制机型上才能复现吗？

### ISSUE THREAD

**Issue by JasonFuuuuuuuu** [modelscope/dash-infer#15]
g8i在120个token的首字延迟上， 14b模型大概是6秒，7b是3.8秒，均无法达到官方0.5s的速度，请问是机器的事吗？还有其他加速办法吗？首字延迟在生产环境非常matter

**Comment by laiwenzh** [comment]
推理的时候cpu占有率打满了吗？

**Comment by laiwenzh** [comment]
![image](https://github.com/modelscope/dash-infer/assets/80147768/0269c121-9e40-4817-a6db-77ac78d1904a)

你可以用htop看一下，cpu使用率都已经达到100%了。如果是x86 cpu的话，性能最佳的情况是物理核打满，不是逻辑核打满，参考图片。如果你的cpu上不是这种形式的占有率，可以试一下手动把num_threads改成你的CPU单个NUMA下的物理核数。

"engine_config": {
    "engine_max_length": 2048,
    "engine_max_batch": 8,
    "do_profiling": false,
    "num_threads": <单个NUMA下的物理核数>,
    "matmul_precision": "medium"
},

**Comment by kzjeef** [comment]
官方数据是使用48 Phy Core，也就是96 vCPU的数据测试得到， ECS默认都是vCPU，所以你这里是相当于6个Phy Core，相当于1/8的计算力，那么首包性能也会等比下降。
