### ISSUE TITLE
RuntimeError: ALLSPARK_UNKNOWN_ERROR

### ISSUE THREAD

**Issue by LiweiPE** [modelscope/dash-infer#17]
I want to use multinode. I followed the guide and changed the config file as:
  "model_name": "Qwen2-7B",
    "model_type": "Qwen_v20",
    "model_path": "~/dashinfer_models/",
    "data_type": "float32",
    "device_type": "CPU",
    "device_ids": [
        0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    ],
    "multinode_mode": true,
At the begining, I have the error with git version. It seems after converting to dashInfer model the metadata has not saved correctly so I changed the version manually.
![image](https://github.com/modelscope/dash-infer/assets/48242387/312e9463-6a0f-40d3-b6f2-bfe11a14765a)
Then I got a Unknown error from ALLSPARK:
![image](https://github.com/modelscope/dash-infer/assets/48242387/53bce7a7-c94e-45b4-9a90-1c049d64bd78)
CPU info is this:
![image](https://github.com/modelscope/dash-infer/assets/48242387/829e8c81-e411-4114-b917-ab0aee8df40d)

**Comment by laiwenzh** [comment]
Have you installed numactl and do you have permission to set cpu affinity?
For multi-NUMA inference, dashinfer uses mpirun + numactl to bind cpu cores. This approach requires --cap-add SYS_NICE --cap-add SYS_PTRACE --ipc=host arguments when creating containers by docker run.
https://github.com/modelscope/dash-infer/blob/main/documents/EN/examples_python.md#multi-numa-inference

**Comment by LiweiPE** [comment]
thanks, I forgot to install numactl. Its running normally with multi numa now. I have a question, if I set "device_ids": [0,1] it means Im using both NUMA nodes. In my case I have 128 cpus (Numa node 0: 0-31,64-95; Numa node 1: 32-63,96-127), then just setting like this means it is able to use all cpus? How to inference with all cpus available?

**Comment by laiwenzh** [comment]
`device_ids` corresponding to numa nodes, not cpu cores.

You can observe cpu usage by htop. On x86 cpu, you can get best performance when all physical cores are used (in other words, half of all logical cores). In your case, if you find your cores are not fully used, maybe you can manually set num_threads parameter to 32 in the config file.

`num_threads`: The number of threads. For optimal performance, this should match the number of physical cores in a single NUMA node. If set to 0, EngineHelper will automatically parse lscpu output and set the value. If > 0, the set value is used.

**Comment by LiweiPE** [comment]
Thanks for the answer, It all clear now.
