### ISSUE TITLE
能否支持Deepseek V2 Chat 236B?

### ISSUE THREAD

**Issue by huliangbing** [modelscope/dash-infer#2]
非常好的开源项目，借鉴了fastllm，看到使用CPU在生产环境下就能快速并发推理MOE大模型的可能！！！
请问什么时候支持Deepseek V2 Chat 236B (21B激活量)。目前fastllm已经支持4位量化版，在阿里云Intel 32核,192GB内存上跑，大概是3-5token/s

**Comment by kzjeef** [comment]
感谢关注。

DashInfer项目创立和开发比较久了，大概是GPT2/3的时代，那时候还没有太多的LLM推理的开源项目，尤其是CPU上，在开发演进的过程中也不断的升级最新的LLM推理范式比如Continuous batching，才能够更好的服务并发调用的大模型服务端，fastllm是个非常优秀的开源项目， 在一些必须的设计上，比如CB上大家有共识，仅此而已。

MoE 模型的支持以及高性能的4bit量化在我们的roadmap上的，我们也会支持Deepseek V2 模型。

**Comment by huliangbing** [comment]
期待支持Deepseek v2
