### ISSUE TITLE
当prompt_token 超过模型支持的最大长度时, 程序就恢复不了, 一直返回报错信息

### ISSUE THREAD

**Issue by yejunjin** [modelscope/dash-infer#28]
在dashinfer集成进fastchat过程中，~~当prompt token超过engine_max_length时~~ 当.generation_config.max_length < prompt token <  .engine_config.engine_max_length，程序恢复不了。

**Comment by yejunjin** [comment]
当config.json文件中，.engine_config.engine_max_length = 128, .generation_config.max_length = 64, 输入提问长度80左右，就会复现。

复现日志如下：
![image](https://github.com/modelscope/dash-infer/assets/25998993/fad4f104-0fe2-4ac2-a194-6363a9127ec4)

原因：主要是https://github.com/modelscope/dash-infer/blob/40cddfd6b4cc0a0c75141c3cf5fd35a572c4d3b9/csrc/core/model/model.cpp#L403 这段代码没有进行status判断，返回了错误状态也继续执行了。

**Comment by chuanzhubin** [comment]
赞
