### ISSUE TITLE
CPU specifications for Qwen2-7B models

### ISSUE THREAD

**Issue by LiweiPE** [modelscope/dash-infer#37]
I would like to know what should it be the minimum requirement specifications for running 7B models. I have this configuration and only can run 1.5B with average throughput 8.1 token/s.
![image](https://github.com/user-attachments/assets/80822c19-855f-4516-a040-ec0f429cfa26)
![image](https://github.com/user-attachments/assets/5e3c557c-10b5-46f8-952a-370147dcea50)
![image](https://github.com/user-attachments/assets/853010aa-9065-4279-91d3-bc6296d515d4)

**Comment by laiwenzh** [comment]
1B = 1,000,000,000
Model weights are stored in float, 4 bytes.
1000000000 * 4 / (1024 * 1024 * 1024) = 3.72 GB
Thus, loading a 7B model requires at least 26GB of memory.
Considering that DashInfer may reorder weights for best performance during the inference process, it is desirable to have more than twice the memory space (>= 52GB). But this number is not strictly tested.
