### ISSUE TITLE
x86平台前面都没报错，最后一步报错了。

### ISSUE THREAD

**Issue by 983183947** [modelscope/dash-infer#4]
<img width="1368" alt="image" src="https://github.com/modelscope/dash-infer/assets/25240344/7224a45e-0d46-4157-89f6-ee48c609bdfc">

**Comment by kzjeef** [comment]
是在什么虚拟机？ 或者看下这个命令：  `lscpu`  的输出？

**Comment by 983183947** [comment]
<img width="1013" alt="image" src="https://github.com/modelscope/dash-infer/assets/25240344/6da23c60-e71e-4a98-8971-ddfa64f180c5">

**Comment by kzjeef** [comment]
这个CPU 太旧了，不支持任何fp16的指令，demo默认的推理是bf16的， 你可以换新一点的CPU试一下， 如果可能得话，最好用ECS上的第八代ECS，那个CPU不仅支持bf16精度，还可以用amx指令加速计算。

**Comment by laiwenzh** [comment]
"engine_config": {
    "engine_max_length": 2048,
    "engine_max_batch": 8,
    "do_profiling": false,
    "num_threads": 0,
    "matmul_precision": "medium"
},
看起来你的cpu只能用fp32推理，可以把config文件的matmul_precision改成high。
