### ISSUE TITLE
First token latency measurement

### ISSUE THREAD

**Issue by LiweiPE** [modelscope/dash-infer#40]
Hello, I used the performance test script. I saw two measurements which are avg_context_time and avg_generate_time. Do these two values correspond to first token latency and total latency?
![image](https://github.com/user-attachments/assets/c5e55895-db6a-4c13-b9b5-9d5e6333784d)

**Comment by kzjeef** [comment]
Hi, Thanks for test DashInfer, 

generally, you can mapping this two concept by: 
avg TTFT = avg_context_time
total RT = avg_generate_time + avg_context_time
