### ISSUE TITLE
print输出推理结果的疑问

### ISSUE THREAD

**Issue by liukangjia666** [modelscope/dash-infer#5]
prompt_list, gen_cfg_list = create_test_prompt(
    engine_helper.default_gen_cfg)
request_list = engine_helper.create_request(prompt_list, gen_cfg_list)

gen = engine_helper.process_one_request_stream(request_list[0])
for part in gen:
    clear_output(wait=True)
    print(f"Response:\n{part}")
这个是我看官方的流式输出的样例这样写的确实能流式输出结果
Response:
您好！很高兴见到您。有什么我能帮助您的吗？

但是结果输出完成后下面的信息还是会一直输出，请问怎么回事，还有就是直接返回结果的函数是什么呢，我试了 engine_helper.process_one_request，和另一个输出的是None,怎么直接return
I20240528 17:51:39.408087  1806 model.cpp:483] Stop request with request id: 0000000000000000000000000000042
I20240528 17:51:39.410692  1846 as_engine.cpp:1606] [Qwen1.5-1.8B-Chat_cpu_single_float32] request finished with uuid: 0000000000000000000000000000042

**Comment by liukangjia666** [comment]
** text input **
<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
你好<|im_end|>
<|im_start|>assistant

** text output **
你好！有什么我能为你做的吗？

现在只有一个疑问了，text output的内容哪个函数可以直接获取到呢

**Comment by laiwenzh** [comment]
text output存储在request.out_text字段，比如你传进去的是request_list，推理完之后print(request_list[0].out_text)就可以了

**Comment by liukangjia666** [comment]
I20240529 17:12:30.462270  8460 model.cpp:483] Stop request with request id: 0000000000000000000000000000012
I20240529 17:12:30.462356  8468 as_engine.cpp:1606] [Qwen1.5-1.8B-Chat_cpu_single_float32] request finished with uuid: 0000000000000000000000000000012
I20240529 17:12:30.462580  8468 as_engine.cpp:1641] | AllsparkStat | Req: Running: 0 Pending: 0 	 Prompt: 0 T/s  Gen: 0.134532 T/s   请问这种输入日志在哪关闭

**Comment by liukangjia666** [comment]
> 文本输出存储在request.out_text 字段，比如你传进去的是request_list，推理完之后print(request_list[0].out_text)就可以了

**Comment by Arthesfan** [comment]
> I20240529 17:12:30.462270 8460 model.cpp:483] Stop request with request id: 0000000000000000000000000000012 I20240529 17:12:30.462356 8468 as_engine.cpp:1606] [Qwen1.5-1.8B-Chat_cpu_single_float32] request finished with uuid: 0000000000000000000000000000012 I20240529 17:12:30.462580 8468 as_engine.cpp:1641] | AllsparkStat | Req: Running: 0 Pending: 0 Prompt: 0 T/s Gen: 0.134532 T/s 请问这种输入日志在哪关闭

可以把这个环境变量设置高一些：HIE_LOG_LEVEL
export HIE_LOG_LEVEL=3

**Comment by rickywu** [comment]
怎么解决一直输出的问题
